Vagrant.configure("2") do |config|
  config.vm.box = "saucy64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['cookbooks', '../cookbooks']
    chef.add_recipe 'apt'
    chef.add_recipe 'git'
    chef.add_recipe 'warden'
  end
end

